### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by IraSoro** [IraSoro/peri#63]
Implement unit tests for cycle's calculations logic, such as pregnancy chance, current day etc.

Include possibility to fake current date and remove all template functions in the storage module (emptyArray, singleArray etc.)

**Comment by imblowfish** [comment]
Please completely the task description

**Comment by imblowfish** [comment]
`App.test.tsx` failed because of

```
    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/imblowfish/Documents/projects/peri/node_modules/@IraSoro/ionic-datetime-picker/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import DatePicker from './components/DatePicker';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      24 | import { cycle_days, period_days } from '../data/SelectConst'
      25 |
    > 26 | import { DatePicker } from '@IraSoro/ionic-datetime-picker'
         | ^
      27 | import type { Cycle } from '../data/ClassCycle';
      28 | import { importConfig } from '../data/Config';
      29 | import { storage } from '../data/Storage';

      at Runtime.createScriptFromCode (node_modules/react-scripts/node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/modals/WelcomeModal.tsx:26:1)
      at Object.<anonymous> (src/pages/TabHome.tsx:27:1)
      at Object.<anonymous> (src/App.tsx:17:1)
      at Object.<anonymous> (src/App.test.tsx:3:1)
```

As I know this package will be removed in #62

**Comment by imblowfish** [comment]
Same error with `WelcomeModal.test.tsx`

**Comment by imblowfish** [comment]
I can't cover the calculation tests right now, because all this logic are placed inside hooks

I think we should return to them later when we'll move all calculation's logic inside the separated module

**Comment by imblowfish** [comment]
> I can't cover the calculation tests right now, because all this logic are placed inside hooks
> 
> I think we should return to them later when we'll move all calculation's logic inside the separated module

Added new task draft, @IraSoro please check https://github.com/users/IraSoro/projects/4/views/4?pane=issue&itemId=32107895
